### ISSUE TITLE
Repair t_basesock test on Linux

### ISSUE THREAD

**Issue by adminspotter** [adminspotter/r9#171]
In the `DeleteUnix` test for the basesock, we're updating the `rdbuf` of `std::clog` so we can grab the log messages we're spitting out.  For whatever reason, Linux doesn't like it when we set the `rdbuf` back to its original value, and blows up.  We've got `#ifdef __APPLE__` guards around those lines for now, which is kind of ridiculous, and limits the scope of our tests on non-OSX platforms.

**Comment by adminspotter** [comment]
A backtrace from the test:
```
#0  0x00007ffff76c2f7a in std::basic_stringstream<char, std::char_traits<char>, std::allocator<char> >::~basic_stringstream() () from /lib64/libstdc++.so.6
#1  0x00000000004069da in BasesockTest_DeleteUnix_Test::TestBody (
    this=0x61e540) at t_basesock.cc:211
    ...
```
The segfault is in the stringstream destructor.
